### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by Z0mb1ee** [webtorrent/webtorrent-cli#209]
**What version of this package are you using?**
tried to install today
**What operating system, Node.js, and npm version?**
linux mint 20.2, node v17.3.0, npm 8.3.0
**What happened?**
this
![image](https://user-images.githubusercontent.com/83365978/147881945-86c7ab34-9893-4545-9451-977b2b639eb8.png)

**What did you expect to happen?**
webtorrent being installed
**Are you willing to submit a pull request to fix this bug?**

**Comment by DiegoRBaquero** [comment]
You need to install git 

Diego

**Comment by Z0mb1ee** [comment]
i installed it and now i have this 
![image](https://user-images.githubusercontent.com/83365978/147882232-b015e6eb-595f-4426-94ff-055d727b3e73.png)

**Comment by Z0mb1ee** [comment]
i get this when i run it as administrator
![image](https://user-images.githubusercontent.com/83365978/147882278-3c5337bc-49e8-4599-b6c3-1fd3461e8f84.png)

**Comment by DiegoRBaquero** [comment]
npm doesn’t have access to usr folder.

Out of the scope for this issue. Google will give you answers

Diego

**Comment by Nan0Scho1ar** [comment]
I can replicate the `permission denied (publickey)` issue by running `sudo npm install -g webtorrent-cli` using the latest version of npm.

**Comment by Z0mb1ee** [comment]
so i should try an older version of npm?

**Comment by Nan0Scho1ar** [comment]
I suspect the issue may be the usage of the ssh url (private) of the git repository rather than http

**Comment by Z0mb1ee** [comment]
and what should i do?

**Comment by Nan0Scho1ar** [comment]
> and what should i do?

Well I'm not certain that is the issue, because the package installs fine locally, which is strange. I've never had issues installing other packages globally. I will try including my ssh keys for the root user and see if it will then let my install globally.

**Comment by Z0mb1ee** [comment]
is there a way to install webtorrent-cli with something else? i mean if i can download this repo as zip and install it manually

**Comment by Nan0Scho1ar** [comment]
Copying my ssh keys over to /root resolved the permission issue caused by using a ssh url rather than https, though this should not be necessary.

**Comment by Nan0Scho1ar** [comment]
I have created a PR which should resolve this issue.

**Comment by catfrightening** [comment]
i cannot even install webtorrent-cli when it says it finished installing webtorrent i cannot run the command. so i don't even know if its installed or not. and then i get warnings that say ecstatic this package is unmaintained and deprecated 
and xmldom this package is unmaintained and deprecated.

**Comment by aj-arts** [comment]
the pr @Nan0Scho1ar created how do i install it

**Comment by aris-sk** [comment]
"""
npm ERR! Linux 5.10.0-051000-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "webtorrent-cli"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:190:5
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aris/bin/adventofcode/npm-debug.log
"""
i get this error output. can anyone help?

**Comment by Z0mb1ee** [comment]
it still doesn't work for me and i still get the same errors. should i try a different verison of npm?

**Comment by Z0mb1ee** [comment]
using npm 5.6.0 solved the issue
